# Generated by Django 6.1 on 2026-08-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='member_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
