# Generated by Django 6.1 on 2026-09-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipapplication_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='membership_proofs/'),
        ),
    ]
