# Generated by Django 6.1 on 2026-09-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershipapplication_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='member_qr_codes/'),
        ),
    ]
