# Generated by Django 6.1 on 2026-08-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
