# Generated by Django 6.1 on 2026-08-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='locked_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
