# Generated by Django 6.1 on 2026-08-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sharetransaction',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sharetransaction',
            name='shares',
            field=models.IntegerField(),
        ),
    ]
