# Generated by Django 6.1 on 2026-08-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_sharetransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
