# Generated by Django 6.1 on 2026-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_sharetransaction_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='month',
            field=models.IntegerField(),
        ),
    ]
