# Generated by Django 6.1 on 2026-08-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
