# Generated by Django 6.1 on 2026-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_loan_remaining_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='received_by',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='loan_repayments/'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
