# Generated by Django 6.1 on 2026-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MEMBER', 'Member'), ('FINANCE', 'Finance Officer'), ('ADMINISTRATOR', 'Administrator'), ('DEVELOPER', 'Developer')], default='USER', max_length=20),
        ),
    ]
